version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: corteXpres_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corteXpres
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: corteXpres_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - keycloak  # 
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=corteXpres
      - PORT=3000
    volumes:
      - .:/app  #

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080" #

volumes:
  db_data:
